### ISSUE TITLE
作者你好，我把你的最新代码放上去，依然不行，不知道咋回事，请大侠再看看，我是昨天向你提问的

### ISSUE THREAD

**Issue by spiritfox358** [wusfen/wu.tmpl.js#10]
![image](https://user-images.githubusercontent.com/32157422/55307993-e2934380-548b-11e9-8873-63816b8d6043.png)
我把你的最新代码放上去，依然不行，不知道咋回事，请大侠再看看

_Originally posted by @spiritfox358 in https://github.com/wusfen/wutpl/issues/9#issuecomment-478454637_

**Comment by wushufen** [comment]
见 #9
