### ISSUE TITLE
wu.tmpl可以增加commonjs支持吗

### ISSUE THREAD

**Issue by slince** [wusfen/wu.tmpl.js#2]
因为需要用到webpack打包项目，tu。tmpl不支持commonjs用起来比较不方便

**Comment by wushufen** [comment]
应该是 webpack 打包时，改变了代码最后一行的 `this`的指向，在前端是代表 `window`。
你可以先暂时把最后一个 `this`改成 `window`再打包看看。
后续会处理

**Comment by wushufen** [comment]
已处理
