### ISSUE TITLE
渲染图片第一次会直接渲染'{{item.img}}'字符串，导致报错。

### ISSUE THREAD

**Issue by jackrouse** [wusfen/wu.tmpl.js#6]
![image](https://user-images.githubusercontent.com/23158775/42140997-5ee6f4c6-7dd8-11e8-877b-c0eccd0a4d44.png)

**Comment by jackrouse** [comment]
感觉可以通过先data-src的方式绑定，渲染完成后再替换为真实路径。

**Comment by wushufen** [comment]
你好，已处理
