### ISSUE TITLE
IE11上必须加上以下代码才不会报错

### ISSUE THREAD

**Issue by hzjianglf** [wusfen/wu.tmpl.js#7]
`var DONT_ENUM = "propertyIsEnumerable,isPrototypeOf,hasOwnProperty,toLocaleString,toString,valueOf,constructor".split(","),
    hasOwn = ({}).hasOwnProperty;
for (var i in {
        toString: 1
    }) {
    DONT_ENUM = false;
}

Object.keys = Object.keys || function (obj) { //ecma262v5 15.2.3.14
    var result = [];
    for (var key in obj)
        if (hasOwn.call(obj, key)) {
            result.push(key);
        }
    if (DONT_ENUM && obj) {
        for (var i = 0; key = DONT_ENUM[i++];) {
            if (hasOwn.call(obj, key)) {
                result.push(key);
            }
        }
    }
    return result;
};`

**Comment by wushufen** [comment]
较旧的浏览器不支持 `Object.keys`

**Comment by hzjianglf** [comment]
强烈建议加上以上代码，以适合各种浏览器

**Comment by hzjianglf** [comment]
> 较旧的浏览器不支持 `Object.keys`

强烈建议加上以上代码，以适合各种浏览器

**Comment by wushufen** [comment]
谢谢你的反馈，最新版没有用到Object.keys了，欢迎参考文档试用。

**Comment by hzjianglf** [comment]
> 谢谢你的反馈，最新版没有用到Object.keys了，欢迎参考文档试用。

为了在模板中使用js代码，并且与jsp不冲突，记得在原先版本中，可以修改一个字符后，使用以下模板：


<script id="tmpl" type="text/tmpl">
--
  |  
  |  
  | <div class="news">
  | <# var topicnum=1; var perfix="http://www.com.cn/url.jsp?url=" ; #>
  | {{each item itemm index}}
  | <# var datediff=(Date.parse(new Date())/1000 - itemm.update_time)/3600/24;#>
  | <# if (index==0 && datediff<=10 ) { #>
  | <div class="news-in">
  | <a href="{{itemm.url}}" target="_blank">
  | <img class="lazytoppic" src="{{perfix}}{{itemm.thumb_url}}" data-echo="" width="100%">
  | </a>
  | <span class="news-intitle" style="display:block">
  | <i class="hot-one">{{topicnum}}</i>
  | {{itemm.title}}
  | </span>
  | </div>
  | <div class="contents">
  | <a href="{{itemm.url}}" target="_blank">
  | <i class="update-time">{{=trans_unixtime_to_ymd(itemm.update_time)}}</i>{{itemm.digest}}</a>
  | </div>
  | <# } else { #>
  | <# if (index==0) { #>
  | <div class="morenews" style="border-top:none">
  | <# } else { #>
  | <div class="morenews">
  | <# }; #>
  | <div class="morenews-pic">
  | <a href="{{itemm.url}}" target="_blank">
  | <img class="lazy" src="{{perfix}}{{itemm.thumb_url}}" data-echo="" width="50px" height="50px">
  | </a>
  | </div>
  | <div class="morenews-txt-box">
  | <i class="hot-one">{{topicnum}}</i>
  | <a href="{{itemm.url}}" target="_blank">
  | <span class="morenews-title">{{itemm.title}}</span>
  | <span class="morenews-digest">
  | <i class="update-time">{{=trans_unixtime_to_ymd(itemm.update_time)}}</i>{{itemm.digest}}</span>
  | </a>
  | </div>
  | </div>
  |  
  | <# }; topicnum++; #>
  | {{/each}}
  | </div>
  |  
  | </script>
  | <script type="text/javascript" src="wu.tmpl.js"></script>
  | <script type="text/javascript">
  | var source = document.getElementById('tmpl').innerHTML;
  | document.getElementById('result').innerHTML = wu.tmpl(source, data);;
  | </script>

请问在最新版本中，需要改哪里才能适应 <# }; topicnum++; #>  类似js语句 。谢谢！！

**Comment by wushufen** [comment]
@hzjianglf 建议数据跟模板分离，变量定义在data中传给模板。混写是非常不好的。
