### ISSUE TITLE
如何获取循环对象的本身

### ISSUE THREAD

**Issue by spiritfox358** [wusfen/wu.tmpl.js#8]
我需要在标签上绑定JSON.stringify(list[i]) 这种形式的，请问如何实现

**Comment by wushufen** [comment]
你好，可以把你的代码贴出来吗

**Comment by spiritfox358** [comment]
![image](https://user-images.githubusercontent.com/32157422/54586673-ba055580-4a58-11e9-9259-fec8e8efcf78.png)
 怎么将这个item转为string类型，而不是对象。我微信 spiritfox358

**Comment by wushufen** [comment]
你好，你可以传一个 `stringify` 函数进去呢
```html
<div id="tpl">
  {{ stringify(item) }}
</div>
<script>
wutpl(tpl, {
  item: {obj: true},
  stringify: function(value){
    return JSON.stringify(value)
  }
})
</script>
```
或者可以更新下版本，之前的版本是限制访问全局变量（如JSON）的，现在你可以这样写
``html
{{ JSON.stringify( item ) }}
```
