### ISSUE TITLE
嵌套循环报错了

### ISSUE THREAD

**Issue by spiritfox358** [wusfen/wu.tmpl.js#9]
![%Y0~(YV$WH@X6 PD_G%X~7O](https://user-images.githubusercontent.com/32157422/55298816-646e7700-5462-11e9-9ef6-c4cba7faa01f.png)
![ALO4A9OO7WRBPK5KXCK$JW2](https://user-images.githubusercontent.com/32157422/55298838-87992680-5462-11e9-8f3a-5659b7d19e50.png)
大侠帮忙看看

**Comment by wushufen** [comment]
你好，谢谢指正，已修复。
原因是最近修改的 each 没绑定 this ，导致嵌套的 this 不对

**Comment by spiritfox358** [comment]
![image](https://user-images.githubusercontent.com/32157422/55307993-e2934380-548b-11e9-8873-63816b8d6043.png)
我把你的最新代码放上去，依然不行，不知道咋回事，请大侠再看看

**Comment by wushufen** [comment]
Duplicate of #10 
不好意思，对象each没绑定this，之前只处理了数组，已处理~ 感谢指定

**Comment by spiritfox358** [comment]
如何拿到遍历对象的index呢？希望作者解答

**Comment by spiritfox358** [comment]
@wusfen 如何拿到遍历对象的index呢？希望作者解答

**Comment by wushufen** [comment]
@spiritfox358 已增加index参数，见文档
